package model;

import org.springframework.stereotype.Component;

import model.enums.UserType;
import model.userhierarchy.Faculty;
import model.userhierarchy.Guest;
import model.userhierarchy.HeadLabCoordinator;
import model.userhierarchy.LabManager;
import model.userhierarchy.Researcher;
import model.userhierarchy.Student;
import model.userhierarchy.User;

/**
 * Factory for creating the correct {@link User} subclass based on {@link UserType}.
 * With JPA {@code @GeneratedValue} the ID is assigned on persist, so the factory
 * passes 0 and the repository assigns the real ID during {@code save()}.
 */
@Component
public class UserFactory {

    /** Creates a user without an explicit ID (ID is auto-generated by JPA). */
    public User createUser(String email, String username, String password, int verificationNum, UserType type) {
        return createUser(0, email, username, password, verificationNum, type);
    }

    public User createUser(int id, String email, String username, String password, int verificationNum, UserType type) {
        switch (type) {
            case STUDENT:
                return new Student(id, email, username, password, verificationNum);
            case FACULTY:
                return new Faculty(id, email, username, password, verificationNum);
            case GUEST:
                return new Guest(id, email, username, password, verificationNum);
            case RESEARCHER:
                return new Researcher(id, email, username, password, verificationNum);
            case LABMANAGER:
                return new LabManager(id, email, username, password, verificationNum);
            case HEADLABCOORDINATOR:
                return new HeadLabCoordinator(id, email, username, password, verificationNum);
            default:
                return null;
        }
    }
}
