CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255),
    university_affiliated BOOLEAN,
    verification_num INT,
    is_department_approved BOOLEAN,
    user_type VARCHAR(30)
);
