CREATE TABLE reservations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    equipment_id INT,
    user_id INT,
    status VARCHAR(20),
    total_owed INT,
    deposit_amount INT,
    CONSTRAINT fk_reservation_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id),
    CONSTRAINT fk_reservation_user FOREIGN KEY (user_id) REFERENCES users(id)
);
